name: Code Style Check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    style:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10" # Update as per your project's Python version

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install black isort

            - name: Check code style
              run: |
                  black --version
                  make check-style
